[versions]
shadow = "8.1.7"
spotless = "6.13.0"
indra = "3.0.1"
paperweight = "1.7.1"

# Version declaration for initial and base platform, Spigot.
api = "1.8.8-R0.1-SNAPSHOT"

[libraries]
platform = { module = "org.spigotmc:spigot-api", version.ref = "api" }

[plugins]
shadow = { id = "io.github.goooler.shadow", version.ref = "shadow" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
indra = { id = "net.kyori.indra", version.ref = "indra" }
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
